name = "dungeon-of-echoes-api"
main = "src/index.js"
compatibility_date = "2026-04-25"

# Bindings (fill after `wrangler d1 create`)
[[d1_databases]]
binding = "DB"
database_name = "dungeon_of_echoes"
database_id = "2234eb19-06bf-4eb2-b242-6fcacf7d99eb"

[vars]
# Comma-separated allowed origins for CORS (Pages URL + your custom domain later)
ALLOWED_ORIGINS = "https://dungeon-of-echoes-9a2.pages.dev"

